### PR TITLE
[TASK] Migrate to use ESM modules for TYPO3 v12

### PR DESCRIPTION
**Pull request by bnf**
Requires at least 12.4.5 for TYPO3 v12 as a bug needed to be fixed first:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/80174

### CODE REVIEW

**Comment by tritum** [comment]
Thank you @bnf for your contribution. 12.4.5 has been released. Will test today and merge asap.

**Comment by tritum** [comment]
@bnf Do you want to fix the TypoScript Linting?

**Comment by bnf** [comment]
@tritum yup, done!

**Comment by tritum** [comment]
The migration to ESM modules has been done when adding v13 compatibility, see #75. The approach uses the recommended stuff documented in https://docs.typo3.org/c/typo3/cms-form/main/en-us/I/Concepts/FormEditor/Index.html#concepts-formeditor-basicjavascriptconcepts-registercustomjavascriptmodules

**Pull request closed without merging**
